import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import axios from "axios";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [posts, setPosts] = useState([]);
  
  const fetchPosts = async () => {
    const { data } = await axios.get("/api/blog");
    setPosts(data.posts);
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  console.log(posts);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next Blog</h1>

        <p className={styles.description}>
          Get started by reading and writing blogs.
        </p>

        <div className={styles.btnContainer}>
          <Button href="/create" label="Create a new post" />
        </div>

        <div className={styles.grid}>
          {posts?.map(({ post }) => {
            return (
              <Link href="https://nextjs.org/docs" key={post?.id}>
                <a className={styles.card}>
                  <h2>{post?.title} &rarr;</h2>
                  <p>{post?.content}</p>
                </a>
              </Link>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        &copy; All Rights Reserved - 2022
      </footer>
    </div>
  );
}

export const Button = ({ href = "", label, type = "button" }) => {
  const router = useRouter();
  return (
    <button
      className={styles.createBtn}
      onClick={() => href !== "" && router.push(href)}
      type={type}
    >
      {label}
    </button>
  );
};
