import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import axios from "../lib/axios";
import styles from "../styles/Home.module.css";
import { Button } from "../components/Button";

export default function Home() {
  const [posts, setPosts] = useState([]);

  const postSlice = useSelector((state) => state);

  console.log(postSlice);

  const fetchPosts = async () => {
    const { data } = await axios.get("/posts");
    setPosts(data.posts);
  };

  useEffect(() => {
    fetchPosts();
  }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Next Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next Blog</h1>

        <p className={styles.description}>
          Get started by reading and writing blogs.
        </p>

        <div className={styles.btnContainer}>
          <Button href="/create" label="Create a new post" />
        </div>

        <div className={styles.grid}>
          {posts?.map((post) => {
            return (
              <Link href={`/post/${post?.id}`} key={post?.id}>
                <a className={styles.card}>
                  <h2>{post?.title} &rarr;</h2>
                  <p>{post?.content}</p>
                </a>
              </Link>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        &copy; All Rights Reserved - 2022
      </footer>
    </div>
  );
}


